name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: input
    id: title
    attributes:
      label: Feature Title
      description: A concise title for your feature request
      placeholder: "Add quantum-inspired encryption for secure AI communications"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        - What is the current limitation?
        - Who is affected by this problem?
        - How often does this problem occur?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred solution in detail
      placeholder: |
        - How should this feature work?
        - What would the user experience be like?
        - Are there any technical considerations?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature belong to?
      options:
        - AI/ML Enhancement
        - Communication Protocols
        - User Interface
        - Performance Optimization
        - Security & Privacy
        - Testing & Quality
        - Developer Experience
        - Analytics & Monitoring
        - Integration & APIs
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would be beneficial
        - High - Important for workflow
        - Critical - Blocking current usage
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        - What other solutions have you considered?
        - What are the pros/cons of each approach?
        - Are there existing workarounds?

  - type: textarea
    id: research
    attributes:
      label: Research & References
      description: Any relevant research papers, articles, or implementations?
      placeholder: |
        - Academic papers or research
        - Similar implementations in other projects
        - Industry standards or best practices
        - Competitive analysis

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Designs
      description: Visual representations of your feature idea
      placeholder: Drag and drop images, sketches, or design files here

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Check all that apply
      options:
        - label: This feature requires breaking API changes
        - label: This feature needs new dependencies
        - label: This feature affects performance significantly
        - label: This feature requires additional permissions
        - label: This feature needs backend/server changes
        - label: This feature affects security model
        - label: I'm willing to contribute to implementation

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know when this feature is complete?
      placeholder: |
        - Feature works as described
        - Performance meets requirements
        - Tests are implemented and passing
        - Documentation is updated
        - No regressions in existing functionality

  - type: input
    id: timeline
    attributes:
      label: Desired Timeline
      description: When would you like to see this feature implemented?
      placeholder: "Next release / Q2 2024 / No specific timeline"

  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: What positive impact would this feature have?
      placeholder: |
        - User experience improvements
        - Performance gains
        - New use cases enabled
        - Competitive advantages
        - Technical debt reduction

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have provided detailed information
          required: true
        - label: I have considered alternative solutions
          required: true
        - label: I understand this is a request, not a guarantee
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be relevant
      placeholder: Links, references, or additional thoughts